services:
  ### Postgresdatabase
  pgdatabase:
    container_name: pgdatabase_container
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432" 
    profiles: ["pgdatabase"]
  
  ### Pgadmin Ui
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"  
    profiles: ["pgadmin"]

  ### Prefect Database
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orion
    expose:
      - 5432
    volumes: 
      - db:/var/lib/postgresql/data
    profiles: ["oriondb"]

  ### Prefect Orion API
  orion:
    image: prefecthq/prefect:2.7.7-python3.11
    volumes:
      - prefect:/root/.prefect
    entrypoint: ["prefect", "orion", "start"]
    environment:
      - PREFECT_API_URL=http://host.docker.internal:4200/api
      - PREFECT_ORION_API_HOST=0.0.0.0
      - PREFECT_ORION_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@database:5432/orion
    ports:
      - 4200:4200
    depends_on:
      - database
    profiles: ["orion"]

  ### Prefect CLI
  cli:
    image: prefecthq/prefect:2.7.7-python3.11
    entrypoint: ./docker-entrypoint.sh
    working_dir: "/root/flows"
    volumes:
      - "./flows:/root/flows"
    environment:
      - PREFECT_API_URL=http://orion:4200/api
    profiles: ["cli"]
      
volumes:
  prefect:
  db:
