services:
  ### Postgresdatabase
  pgdatabase:
    container_name: pgdatabase_container
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ny_db:/var/lib/postgresql/data
    ports:
      - "5432:5432" 
    profiles: ["pgdatabase"]
  
  ### Pgadmin Ui
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"  
    profiles: ["pgadmin"]

  ### Prefect Orion API
  orion:
    container_name: orion
    image: prefecthq/prefect:2.7.7-python3.11
    volumes:
      - prefect:/root/.prefect
    entrypoint: ["prefect", "orion", "start"]
    environment:
      - PREFECT_API_URL=${PREFECT_API_URL}
      - PREFECT_ORION_API_HOST=0.0.0.0
    ports:
      - 4200:4200
    profiles: ["orion"]

  ### Prefect CLI
  cli:
    container_name: cli
    image: prefecthq/prefect:2.7.7-python3.11
    entrypoint: ./docker-entrypoint.sh
    working_dir: "/root/flows"
    volumes:
      - "./flows:/root/flows"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - PREFECT_API_URL=${PREFECT_API_URL}
    profiles: ["cli"]
      
volumes:
  prefect:
  ny_db:
